module.exports.testcases = [{name:'Automated Acceptance Test/Audit - Client Acceptance Part 1.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 2.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 3.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 4.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 5.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 6.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 7.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 8.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 9.t'},
{name:'Automated Acceptance Test/Audit - Client Acceptance Part 10.t'},
{name:'Automated Acceptance Test/Audit - Firm side AcceptanceTest.t'},
{name:'Automated Acceptance Test/Audit - Firm side Acceptance Part2.t'},
{name:'Automated Acceptance Test/Audit - Firm side Acceptance Part3.t'},
{name:'Automated Acceptance Test/Audit - Firm side Acceptance Part4.t'},
{name:'Automated Acceptance Test/Audit - Firm side Acceptance Part5.t'},
{name:'Automated Acceptance Test/Audit - Patch Client Acceptance.t'},
{name:'Automated Acceptance Test/TD-9435 Acceptance test - Content.t'},
{name:'Automated Acceptance Test/AS-1439 Include-Exclude Combined Assertions.t'},
{name:'Automated Acceptance Test/Audit - Firm side AcceptanceTest_POC.t'},
{name:'--------------------------------'},
{name:'Control Matrix and Controls/TD-1652 Control Matrix and Editing Controls.t'},
{name:'--------------------------------'},
{name:'Dialogs/TD-758 Document Properties.t'},
{name:'Dialogs/TD-1546 Risks.t'},
{name:'Dialogs/TD-1602 Reportable Items.t'},
{name:'Dialogs/TD-1617 Controls.t'},
{name:'Dialogs/TD-1679 Import Procedures.t'},
{name:'Dialogs/TD-1707 New Procedures.t'},
{name:'--------------------------------'},
{name:'EP7/TD-2782 EP7 and Logo Preview Functionality.t'},
{name:'--------------------------------'},
{name:'Experimental Test Plans/Audit - Document Translated To Chinese Test.t'},
{name:'Experimental Test Plans/Audit - Patch Test.t'},
{name:'Experimental Test Plans/JenkinsEnableJsrt.t'},
{name:'--------------------------------'},
{name:'FSA/TD-1783 Balances.t'},
{name:'FSA/AS-2567 Configuration Setting Part 1.t'},
{name:'FSA/AS-2567 Configuration Setting Part 2.t'},
{name:'FSA/AS-3029 Multiple FSA Documents.t'},
{name:'FSA/AS-3008 Control Risk.t'},
{name:'--------------------------------'},
{name:'Menus - Areas/TD-1574 Areas menu items - Work Programs and Checklists (Client Side).t'},
{name:'Menus - Areas/TD-1575 Areas menu items - Work Programs and Checklists (Template Side).t'},
{name:'--------------------------------'},
{name:'Menus - Author/TD-1595 Author menu items - Work Programs and Checklists (Template Side).t'},
{name:'--------------------------------'},
{name:'Menus - Document/TD-1545 Document menu items - Work Programs and Checklists (Template Side).t'},
{name:'Menus - Document/TD-1554 Document menu items - Work Programs and Checklists (Client Side).t'},
{name:'Menus - Document/TD-1573 Document menu items - Flat Forms (Client Side).t'},
{name:'Menus - Document/TD-1577 Document menu items - Flat Forms (Template Side).t'},
{name:'Menus - Document/TD-1580 Document menu items - Letters (Template Side).t'},
{name:'Menus - Document/TD-1624 Document menu items - Letters (Client Side).t'},
{name:'--------------------------------'},
{name:'Menus - Help/TD-1570 Help menu items (Template Side).t'},
{name:'Menus - Help/TD-1571 Help menu items (Client Side).t'},
{name:'--------------------------------'},
{name:'Menus - Options/TD-1568 Options Menu Items (Template Side).t'},
{name:'--------------------------------'},
{name:'Menus - Procedures/TD-1553 Procedure menu items - Work Programs and Checklists (Template Side).t'},
{name:'Menus - Procedures/TD-1594 Procedure menu items - Work Programs and Checklists (Client Side).t'},
{name:'--------------------------------'},
{name:'Miscellaneous Document Functionality/TD-191 Highlight External Cells (Template Side).t'},
{name:'Miscellaneous Document Functionality/TD-566 Lock Down.t'},
{name:'Miscellaneous Document Functionality/TD-599 Sign-Offs.t'},
{name:'--------------------------------'},
{name:'Old Test Plans/Audit - Audit Response Table Test.t'},
{name:'Old Test Plans/Audit - Checklist and WPG Menu Test.t'},
{name:'Old Test Plans/Audit - Highlight Procedures Test.t'},
{name:'Old Test Plans/Audit - Smoke Test.t'},
{name:'Old Test Plans/Audit - Template Procedure Update AUD-10547.t'},
{name:'Old Test Plans/Audit - Test CV-5821.t'},
{name:'Old Test Plans/Audit - Test WP-10398.t'},
{name:'Old Test Plans/Audit API/API.t'},
{name:'--------------------------------'},
{name:'Optimiser - AOCR/TD-602 AOCR - FSA Assessment.t'},
{name:'Optimiser - AOCR/TD-603 AOCR - Industry.t'},
{name:'Optimiser - AOCR/TD-973 AOCR - Checklist Responses.t'},
{name:'--------------------------------'},
{name:'Performance Tests/Audit - Generate FSA Performance.t'},
{name:'Performance Tests/Audit - Performance Test 2.t'},
{name:'Performance Tests/Audit - Performance Test.t'},
{name:'Performance Tests/Audit - Risk Load Performance.t'},
{name:'--------------------------------'},
{name:'PMSD/TD-1621 PMSD Functionality.t'},
{name:'--------------------------------'},
{name:'Procedure-Risk-Control deletions/AS-336 Procedure Conditions.t'},
{name:'--------------------------------'},
{name:'Risk Report and Risks/TD-146 Mini-Risk Report.t'},
{name:'Risk Report and Risks/TD-1940 Importing Risks.t'},
{name:'Risk Report and Risks/TD-2212 Risk Report and Editing Risks.t'},
{name:'Risk Report and Risks/TD-5802 Risk Relations.t'},
{name:'--------------------------------'},
{name:'Template Updates/AS-279 Documents Update.t'},
{name:'Template Updates/TD-1302 Procedures Update.t'},
{name:'Template Updates/TD-1302-2 Procedures Update.t'},
{name:'--------------------------------'},
{name:'Test Tools/Any Test Boilerplate/Audit - Any Test Auto-Generate.t'},
{name:'Test Tools/Any Test Boilerplate/Audit - Any Test Boilerplate.t'},
{name:'Test Tools/Create Client Files/Template - Create Client Files.t'},
{name:'Test Tools/Create Master Templates/Audit - Create Master Templates.t'},
{name:'Test Tools/Find Groupings/Audit - Find Groupings.t'},
{name:'--------------------------------'},
{name:'Toolbar Buttons - CaseView Toolbar/TD-1616 Template Toolbar Button Functionality.t'},
{name:'--------------------------------'},
{name:'Training test - TD-11165/TD-11165 Training Test.t'},
{name:'Training Test Plans/Automate Audit Training Test plan AUD-13235/Audit - Sample Test 3.t'},
{name:'Training Test Plans/Automate Audit Training/Automate Audit Training.t'},
{name:'--------------------------------'},
{name:'Unit Tests/Unit Tests - TemplateAudit.t'},
{name:'--------------------------------'},
{name:'Work Program and Checklists - Authoring/TD-567 Conclusion.t'},
{name:'Work Program and Checklists - Authoring/TD-589 Guidance.t'},
{name:'Work Program and Checklists - Authoring/TD-1939 Procedures.t'},
{name:'Work Program and Checklists - Authoring/AS-1588 Common Procedures.t'},
{name:'Work Program and Checklists - Authoring/AS-1588-1 Common Procedures - Creating and Author Levels.t'},
{name:'Work Program and Checklists - Authoring/AS-1588-2 Common Procedures - Inserting Editing and Deleting.t'},
{name:'--------------------------------'},
{name:'Work Program and Checklists - General/AS-250 Procedure Response.t'},
{name:'Work Program and Checklists - General/TD-1764 Procedure Deletion.t'},
{name:'Work Program and Checklists - General/TD-5804 Insert and Delete Procedures.t'},
{name:'Work Program and Checklists - General/TD-5806 Based on Procedure.t'},
{name:'Work Program and Checklists - General/TD-13634 Filter Procedures.t'},
{name:'--------------------------------'},
{name:'AO/AUD-24434 Financial Statement Area.t'},
{name:'AO/TD-144 Distributor Settings.t'},
{name:'AO/TD-145 Areas.t'},
{name:'AO/TD-983 Check For Updates.t'},
{name:'AO/TD-1165 Rollforward.t'},
{name:'AO/TD-1181 Materiality.t'},
{name:'AO/TD-1181-2 Materiality.t'},
{name:'AO/TD-1579 Optimiser.t'},
{name:'AO/TD-1677 Controls.t'},
{name:'AO/TD-1677-2 Controls.t'},
{name:'AO/TD-1686 Risks.t'},
{name:'AO/TD-1765 Completion Responses.t'},
{name:'AO/TD-1828 Industry.t'},
{name:'AO/TD-1941 Reportable Item Options.t'},
{name:'AO/TD-1941-2 Reportable Item Options.t'},
{name:'AO/TD-4414 Engagement Profiles.t'},
{name:'AO/AS-3678 Additional Document Library.t'},
{name:'AO/AS-4332 Automate control Risk and RMM.t'},
{name:'--------------------------------'},
{name:'Audit and Financials Combined files/TD-1693 Audit and Financials Combined File - Update 1.t'},
{name:'Audit and Financials Combined files/TD-1693 Audit and Financials Combined File - Update 2.t'},
{name:'Audit and Financials Combined files/TD-1693 Audit and Financials Combined File - Update 3.t'},
{name:'Audit and Financials Combined files/TD-1693 Audit and Financials Combined File - Update 4.t'},
{name:'Audit and Financials Combined files/TD-1693 Audit and Financials Combined File - Update 5.t'},
{name:'Audit and Financials Combined files/TD-1744 Audit and Financials Combined File - Functionality.t'}]